UPDATE `data` SET `list`='Stewart Alexander' WHERE `list`='Alexander%% Stewart';
UPDATE `data` SET `list`='Jonathan Allen' WHERE `list`='Allen%% Jonathan';
UPDATE `data` SET `list`='Gene Amondson' WHERE `list`='Amondson%% Gene';
UPDATE `data` SET `list`='John B. Anderson' WHERE `list`='Anderson%% John B.';
UPDATE `data` SET `list`='Ross Carl "Rocky" Anderson' WHERE `list`="Anderson%% Ross Carl 'Rocky'";
UPDATE `data` SET `list`='Thomas J. Anderson' WHERE `list`='Anderson%% Thomas J.';
UPDATE `data` SET `list`='Stanford Andress' WHERE `list`='Andress%% Stanford';
UPDATE `data` SET `list`='Frank Atwood' WHERE `list`='Atwood%% Frank';
UPDATE `data` SET `list`='Michael Badnarik' WHERE `list`='Badnarik%% Michael';
UPDATE `data` SET `list`='Gerald Baker' WHERE `list`='Baker%% Gerald';
UPDATE `data` SET `list`='Dennis Andrew Ball' WHERE `list`='Ball%% Dennis Andrew';
UPDATE `data` SET `list`='Andre Barnett' WHERE `list`='Barnett%% Andre';
UPDATE `data` SET `list`='Bob Barr' WHERE `list`='Barr%% Bob';
UPDATE `data` SET `list`='Roseanne Barr' WHERE `list`='Barr%% Roseanne';
UPDATE `data` SET `list`='Barbara Bellar' WHERE `list`='Bellar%% Barbara';
UPDATE `data` SET `list`='David Bergland' WHERE `list`='Bergland%% David';
UPDATE `data` SET `list`='Joseph R. Biden' WHERE `list`='Biden%% Joseph R. Jr';
UPDATE `data` SET `list`='John Birrenback' WHERE `list`='Birrenback%% John';
UPDATE `data` SET `list`='Don Blankenship' WHERE `list`='Blankenship%% Don';
UPDATE `data` SET `list`='R. President Boddie' WHERE `list`='Boddie%% R. President';
UPDATE `data` SET `list`='Jeffery Boss' WHERE `list`='Boss%% Jeffery';
UPDATE `data` SET `list`='Drew Bradford' WHERE `list`='Bradford%% Drew';
UPDATE `data` SET `list`='J. Quinn Brisben' WHERE `list`='Brisben%% J. Quinn';
UPDATE `data` SET `list`='Walt Brown' WHERE `list`='Brown%% Walt';
UPDATE `data` SET `list`='Harry Browne' WHERE `list`='Browne%% Harry';
UPDATE `data` SET `list`='Benjamin "Ben" Bubar' WHERE `list`="Bubar%% Benjamin 'Ben'";
UPDATE `data` SET `list`='Patrick "Pat" Buchanan' WHERE `list`="Buchanan%% Patrick 'Pat'";
UPDATE `data` SET `list`='George H. W. Bush' WHERE `list`='Bush%% George H.W.';
UPDATE `data` SET `list`='George W. Bush' WHERE `list`='Bush%% George W.';
UPDATE `data` SET `list`='Pete Buttigieg' WHERE `list`='Buttigieg%% Pete';
UPDATE `data` SET `list`='David Byrne' WHERE `list`='Byrne%% David';
UPDATE `data` SET `list`='Roger Calero' WHERE `list`='Calero%% Roger';
UPDATE `data` SET `list`='Peter Camejo' WHERE `list`='Camejo%% Peter';
UPDATE `data` SET `list`='Jim Carlson' WHERE `list`='Carlson%% Jim';
UPDATE `data` SET `list`='Brian Carroll' WHERE `list`='Carroll%% Brian';
UPDATE `data` SET `list`='Jimmy Carter' WHERE `list`='Carter%% Jimmy';
UPDATE `data` SET `list`='Darrell Castle' WHERE `list`='Castle%% Darrell L.';
UPDATE `data` SET `list`='Todd Cella' WHERE `list`='Cella%% Todd';
UPDATE `data` SET `list`='Mark Charles' WHERE `list`='Charles%% Mark';
UPDATE `data` SET `list`='Will Christensen' WHERE `list`='Christensen%% Will';
UPDATE `data` SET `list`='Ed Clark' WHERE `list`='Clark%% Edward "Ed"';
UPDATE `data` SET `list`='Bill Clinton' WHERE `list`='Clinton%% Bill';
UPDATE `data` SET `list`='Hillary Clinton' WHERE `list`='Clinton%% Hillary';
UPDATE `data` SET `list`='David Cobb' WHERE `list`='Cobb%% David';
UPDATE `data` SET `list`='Charles Collins' WHERE `list`='Collins%% Charles';
UPDATE `data` SET `list`='Loren Collins' WHERE `list`='Collins%% Loren';
UPDATE `data` SET `list`='Phil Collins' WHERE `list`='Collins%% Phil';
UPDATE `data` SET `list`='Barry Commoner' WHERE `list`='Commoner%% Barry';
UPDATE `data` SET `list`='Richard Congress' WHERE `list`='Congress%% Richard';
UPDATE `data` SET `list`='Peter Crane' WHERE `list`='Crane%% Peter';
UPDATE `data` SET `list`='Jesse Cuellar' WHERE `list`='Cuellar%% Jesse';
UPDATE `data` SET `list`='Daniel Clyde Cummings' WHERE `list`='Cummings%% Daniel Clyde';
UPDATE `data` SET `list`='Andrew Cuomo' WHERE `list`='Cuomo%% Andrew';
UPDATE `data` SET `list`='Ron Daniels' WHERE `list`='Daniels%% Ron';
UPDATE `data` SET `list`='Ronald Daniels' WHERE `list`='Daniels%% Ronald';
UPDATE `data` SET `list`='Roque "Rocky" De La Fuente' WHERE `list`="De La Fuente%% Roque 'Rocky'";
UPDATE `data` SET `list`='Clifton Deberry' WHERE `list`='Deberry%% Clifton';
UPDATE `data` SET `list`='Lane Dennis "Denny"' WHERE `list`='Dennis "Denny"%% Lane';
UPDATE `data` SET `list`='Delmar Dennis' WHERE `list`='Dennis%% Delmar';
UPDATE `data` SET `list`='Earl Dodge' WHERE `list`='Dodge%% Earl';
UPDATE `data` SET `list`='Bob Dole' WHERE `list`='Dole%% Robert';
UPDATE `data` SET `list`='Michael Dukakis' WHERE `list`='Dukakis%% Michael';
UPDATE `data` SET `list`='David Duke' WHERE `list`='Duke%% David';
UPDATE `data` SET `list`='Richard Duncan' WHERE `list`='Duncan%% Richard';
UPDATE `data` SET `list`='Soltysik Emidio "Mimi"' WHERE `list`='Emidio "Mimi"%% Soltysik';
UPDATE `data` SET `list`='Randall F' WHERE `list`='F%% Randall';
UPDATE `data` SET `list`='John Farney' WHERE `list`='Farney%% John';
UPDATE `data` SET `list`='Marsha Feinland' WHERE `list`='Feinland%% Marsha';
UPDATE `data` SET `list`='Lowell Jackson "Jack" Fellure' WHERE `list`='Fellure%% Lowell Jackson "Jack"';
UPDATE `data` SET `list`='Katherine Forbes' WHERE `list`='Forbes%% Katherine';
UPDATE `data` SET `list`='Ralph Forbes' WHERE `list`='Forbes%% Ralph';
UPDATE `data` SET `list`='Gerald Ford' WHERE `list`='Ford%% Gerald';
UPDATE `data` SET `list`='Chris Franklin' WHERE `list`='Franklin%% Chris';
UPDATE `data` SET `list`='Lenora Fulani' WHERE `list`='Fulani%% Lenora';
UPDATE `data` SET `list`='Tulsi Gabbard' WHERE `list`='Gabbard%% Tulsi';
UPDATE `data` SET `list`='William "Bill" Gahres' WHERE `list`="Gahres%% William 'Bill'";
UPDATE `data` SET `list`='C. L. Gammon' WHERE `list`='Gammon%% C. L.';
UPDATE `data` SET `list`='Gary Johnson' WHERE `list`='Gary Johnson';
UPDATE `data` SET `list`='Kathryn Gibson' WHERE `list`='Gibson%% Kathryn';
UPDATE `data` SET `list`='Virgil Goode' WHERE `list`='Goode%% Virgil Hamlin%% Jr.';
UPDATE `data` SET `list`='Al Gore' WHERE `list`='Gore%% Al';
UPDATE `data` SET `list`='Percy L. Greaves' WHERE `list`='Greaves%% Percy L%% Jr.';
UPDATE `data` SET `list`='Deirdre Griswold' WHERE `list`='Griswold%% Deirdre';
UPDATE `data` SET `list`='James "Bo" Gritz' WHERE `list`='Gritz%% James "Bo"';
UPDATE `data` SET `list`='John Hagelin' WHERE `list`='Hagelin%% John';
UPDATE `data` SET `list`='Gus Hall' WHERE `list`='Hall%% Gus';
UPDATE `data` SET `list`='Helen Halyard' WHERE `list`='Halyard%% Helen';
UPDATE `data` SET `list`='Bill Hammons' WHERE `list`='Hammons%% Bill';
UPDATE `data` SET `list`='Thomas Harens' WHERE `list`='Harens%% Thomas';
UPDATE `data` SET `list`='James Harris' WHERE `list`='Harris%% James';
UPDATE `data` SET `list`='Howie Hawkins' WHERE `list`='Hawkins%% Howie';
UPDATE `data` SET `list`='Helen Haylard' WHERE `list`='Haylard%% Helen';
UPDATE `data` SET `list`='James Hedges' WHERE `list`='Hedges%% James';
UPDATE `data` SET `list`='Jim Hedges' WHERE `list`='Hedges%% Jim';
UPDATE `data` SET `list`='Roland Hem' WHERE `list`='Hem%% Roland';
UPDATE `data` SET `list`='Lewin Herberg G.' WHERE `list`='Herberg G.%% Lewin';
UPDATE `data` SET `list`='Jack Herer' WHERE `list`='Herer%% Jack';
UPDATE `data` SET `list`='Jeremy Higgs' WHERE `list`='Higgs%% Jeremy';
UPDATE `data` SET `list`='Paul Hodges' WHERE `list`='Hodges%% Paul';
UPDATE `data` SET `list`='Thomas Conrad "Tom" Hoefling' WHERE `list`='Hoefling%% Thomas Conrad "Tom"';
UPDATE `data` SET `list`='Tom Hoefling' WHERE `list`='Hoefling%% Tom';
UPDATE `data` SET `list`='Mary Cal Hollis' WHERE `list`='Hollis%% Mary Cal';
UPDATE `data` SET `list`='Larry Holmes' WHERE `list`='Holmes%% Larry';
UPDATE `data` SET `list`='Shawn W. Howard' WHERE `list`='Howard%% Shawn W.';
UPDATE `data` SET `list`='Blake Huber' WHERE `list`='Huber%% Blake';
UPDATE `data` SET `list`='Mike Huckabee' WHERE `list`='Huckabee%% Mike';
UPDATE `data` SET `list`='Dario Hunter' WHERE `list`='Hunter%% Dario';
UPDATE `data` SET `list`='Phil Hunter' WHERE `list`='Hunter%% Phil';
UPDATE `data` SET `list`='Tara Renee Hunter' WHERE `list`='Hunter%% Tara Renee';
UPDATE `data` SET `list`='Independent Party Candidate' WHERE `list`='Independent Party Candidate%%';
UPDATE `data` SET `list`='Princess Khadijah Maryam Jacob Fambro' WHERE `list`='Jacob Fambro%% Princess Khadijah Maryam';
UPDATE `data` SET `list`='Jade Simmons' WHERE `list`='Jade Simmons';
UPDATE `data` SET `list`='Charles Jay' WHERE `list`='Jay%% Charles';
UPDATE `data` SET `list`='Jesse Ventura' WHERE `list`='Jesse Ventura';
UPDATE `data` SET `list`='Johnson Jr. James L.' WHERE `list`='Johnson Jr. James L.';
UPDATE `data` SET `list`='Gary Johnson' WHERE `list`='Johnson%% Gary';
UPDATE `data` SET `list`='Sonia Johnson' WHERE `list`='Johnson%% Sonia';
UPDATE `data` SET `list`='Jo Jorgensen' WHERE `list`='Jorgensen%% Jo';
UPDATE `data` SET `list`='Joseph Kishore' WHERE `list`='Joseph Kishore';
UPDATE `data` SET `list`='Levin Julius "Jules"' WHERE `list`='Julius "Jules"%% Levin';
UPDATE `data` SET `list`='Lynn S. Kahn' WHERE `list`='Kahn%% Lynn S.';
UPDATE `data` SET `list`='John Kasich' WHERE `list`='Kasich%% John';
UPDATE `data` SET `list`='Chris Keniston' WHERE `list`='Keniston%% Chris';
UPDATE `data` SET `list`='Alyson Kennedy' WHERE `list`='Kennedy%% Alyson';
UPDATE `data` SET `list`='Willa Kenoyer' WHERE `list`='Kenoyer%% Willa';
UPDATE `data` SET `list`='John Kerry' WHERE `list`='Kerry%% John';
UPDATE `data` SET `list`='Alan Keyes' WHERE `list`='Keyes%% Alan';
UPDATE `data` SET `list`='Ricki Sue King' WHERE `list`='King%% Ricki Sue';
UPDATE `data` SET `list`='Joseph Kishore' WHERE `list`='Kishore%% Joseph';
UPDATE `data` SET `list`='Amy Klobuchar' WHERE `list`='Klobuchar%% Amy';
UPDATE `data` SET `list`='Jeffrey J. Klojzy' WHERE `list`='Klojzy%% Jeffrey J.';
UPDATE `data` SET `list`='Kyle Kenley Kopitke' WHERE `list`='Kopitke%% Kyle Kenley';
UPDATE `data` SET `list`='Laurence Kotlikoff' WHERE `list`='Kotlikoff%% Laurence';
UPDATE `data` SET `list`='Smith L. Neil' WHERE `list`='L. Neil%% Smith';
UPDATE `data` SET `list`='Gloria La Riva' WHERE `list`='La Riva%% Gloria Estella';
UPDATE `data` SET `list`='Michael Laboch' WHERE `list`='Laboch%% Michael';
UPDATE `data` SET `list`='Christopher LaFontaine' WHERE `list`='Lafontaine%% Christopher';
UPDATE `data` SET `list`='Lyndon LaRouche' WHERE `list`='Larouche%% Lyndon%% Jr.';
UPDATE `data` SET `list`='Johnson Lee' WHERE `list`='Lee%% Johnson';
UPDATE `data` SET `list`='Peta Lindsay' WHERE `list`='Lindsay%% Peta';
UPDATE `data` SET `list`='Abram Loeb' WHERE `list`='Loeb%% Abram';
UPDATE `data` SET `list`='Arthur Lowery' WHERE `list`='Lowery%% Arthur';
UPDATE `data` SET `list`='Kurt Lynen' WHERE `list`='Lynen%% Kurt';
UPDATE `data` SET `list`='Bradford Lyttle' WHERE `list`='Lyttle%% Bradford';
UPDATE `data` SET `list`='Roger Macbride' WHERE `list`='Macbride%% Roger';
UPDATE `data` SET `list`='Lester Maddox' WHERE `list`='Maddox%% Lester';
UPDATE `data` SET `list`='Joseph Allen Maldonado' WHERE `list`='Maldonado%% Joseph Allen';
UPDATE `data` SET `list`='John Manimas' WHERE `list`='Manimas%% John';
UPDATE `data` SET `list`='Mark Charles' WHERE `list`='Mark Charles';
UPDATE `data` SET `list`='William A. Marra' WHERE `list`='Marra%% William A.';
UPDATE `data` SET `list`='Andre Marrou' WHERE `list`='Marrou%% Andre';
UPDATE `data` SET `list`='David A. Martin' WHERE `list`='Martin%% David A.';
UPDATE `data` SET `list`='Melvin Mason' WHERE `list`='Mason%% Melvin';
UPDATE `data` SET `list`='Isabell Masters' WHERE `list`='Masters%% Isabell';
UPDATE `data` SET `list`='Michael A. Maturen' WHERE `list`='Maturen%% Michael A.';
UPDATE `data` SET `list`='John McCain' WHERE `list`='McCain%% John';
UPDATE `data` SET `list`='Eugene "Gene" McCarthy' WHERE `list`='Mccarthy%% Eugene "Gene"';
UPDATE `data` SET `list`='Ellen McCormack' WHERE `list`='Mccormack%% Ellen';
UPDATE `data` SET `list`='Keith McCormic' WHERE `list`='Mccormic%% Keith';
UPDATE `data` SET `list`='Valerie McCray' WHERE `list`='Mccray%% Valerie';
UPDATE `data` SET `list`='Frank McEnulty' WHERE `list`='Mcenulty%% Frank';
UPDATE `data` SET `list`='Joe McHugh' WHERE `list`='Mchugh%% Joe';
UPDATE `data` SET `list`='Kevin McKee' WHERE `list`='Mckee%% Kevin';
UPDATE `data` SET `list`='Cynthia McKinney' WHERE `list`='Mckinney%% Cynthia';
UPDATE `data` SET `list`='Harley McLain' WHERE `list`='Mclain%% Harley';
UPDATE `data` SET `list`='Evan McMullin' WHERE `list`='Mcmullin%% Evan';
UPDATE `data` SET `list`='David McReynolds' WHERE `list`='Mcreynolds%% David';
UPDATE `data` SET `list`='Merlin Miller' WHERE `list`='Miller%% Merlin';
UPDATE `data` SET `list`='Romney Mitt' WHERE `list`='Mitt%% Romney';
UPDATE `data` SET `list`='Walter Mondale' WHERE `list`='Mondale%% Walter';
UPDATE `data` SET `list`='Richard Charles Montanye' WHERE `list`='Montanye%% Richard Charles';
UPDATE `data` SET `list`='Brian Moore' WHERE `list`='Moore%% Brian';
UPDATE `data` SET `list`='Monica Moorehead' WHERE `list`='Moorehead%% Monica';
UPDATE `data` SET `list`='Robert Morrow' WHERE `list`='Morrow%% Robert';
UPDATE `data` SET `list`='Dean Morstad' WHERE `list`='Morstad%% Dean';
UPDATE `data` SET `list`='John Richard Myers' WHERE `list`='Myers%% John Richard';
UPDATE `data` SET `list`='Ralph Nader' WHERE `list`='Nader%% Ralph';
UPDATE `data` SET `list`='None Of The Above' WHERE `list`='None Of The Above';
UPDATE `data` SET `list`='None Of The Above' WHERE `list`='None Of These Candidates';
UPDATE `data` SET `list`='Barack H. Obama' WHERE `list`='Obama%% Barack H.';
UPDATE `data` SET `list`='Michelle Obama' WHERE `list`='Obama%% Michelle';
UPDATE `data` SET `list`='Other' WHERE `list`='Others';
UPDATE `data` SET `list`='Brooke H. Paige' WHERE `list`='Paige%% Brooke H.';
UPDATE `data` SET `list`='John Parker' WHERE `list`='Parker%% John';
UPDATE `data` SET `list`='Ron Paul' WHERE `list`='Paul%% Ron';
UPDATE `data` SET `list`='Ronald "Ron" Paul' WHERE `list`='Paul%% Ronald "Ron"';
UPDATE `data` SET `list`='Leonard Peltier' WHERE `list`='Peltier%% Leonard';
UPDATE `data` SET `list`='Mike Pence' WHERE `list`='Pence%% Mike';
UPDATE `data` SET `list`='Dennis Peron' WHERE `list`='Peron%% Dennis';
UPDATE `data` SET `list`='Ross Perot' WHERE `list`='Perot%% Ross';
UPDATE `data` SET `list`='Michael Peroutka' WHERE `list`='Peroutka%% Michael';
UPDATE `data` SET `list`='Howard Phillips' WHERE `list`='Phillips%% Howard';
UPDATE `data` SET `list`='Brock Pierce' WHERE `list`='Pierce%% Brock';
UPDATE `data` SET `list`='Andrew Pulley' WHERE `list`='Pulley%% Andrew';
UPDATE `data` SET `list`='Albert Raley' WHERE `list`='Raley%% Albert';
UPDATE `data` SET `list`='John Rarick' WHERE `list`='Rarick%% John';
UPDATE `data` SET `list`='Ronald Reagan' WHERE `list`='Reagan%% Ronald';
UPDATE `data` SET `list`='Jill Ann Reed' WHERE `list`='Reed%% Jill Ann';
UPDATE `data` SET `list`='Condoleeza Rice' WHERE `list`='Rice%% Condoleeza';
UPDATE `data` SET `list`='Richard Duncan' WHERE `list`='Richard Duncan';
UPDATE `data` SET `list`='Bob Richards' WHERE `list`='Richards%% Bob';
UPDATE `data` SET `list`='Mitt Romney' WHERE `list`='Romney%% Mitt';
UPDATE `data` SET `list`='Deborah Rouse' WHERE `list`='Rouse%% Deborah';
UPDATE `data` SET `list`='Bernie Sanders' WHERE `list`='Sanders%% Bernie';
UPDATE `data` SET `list`='Zachary Scalf' WHERE `list`='Scalf%% Zachary';
UPDATE `data` SET `list`='Scattering' WHERE `list`='Scattering';
UPDATE `data` SET `list`='Benjamin Schawlb' WHERE `list`='Schawlb%% Benjamin';
UPDATE `data` SET `list`='Joe Schriner' WHERE `list`='Schriner%% Joe';
UPDATE `data` SET `list`='Jordan "Cancer" Scott' WHERE `list`='Scott%% Jordan "Cancer"';
UPDATE `data` SET `list`='Jerome M. Segal' WHERE `list`='Segal%% Jerome M.';
UPDATE `data` SET `list`='Dennis Serrette' WHERE `list`='Serrette%% Dennis';
UPDATE `data` SET `list`='Jeanne Shaheen' WHERE `list`='Shaheen%% Jeanne';
UPDATE `data` SET `list`='Frank Shelton Jr.' WHERE `list`='Shelton%% Frank%% Jr.';
UPDATE `data` SET `list`='Peter Sherrill' WHERE `list`='Sherrill%% Peter';
UPDATE `data` SET `list`='Rod Silva' WHERE `list`='Silva%% Rod';
UPDATE `data` SET `list`='Jade Simmons' WHERE `list`='Simmons%% Jade';
UPDATE `data` SET `list`='Mary Ruth Caro Simmons' WHERE `list`='Simmons%% Mary Ruth Caro';
UPDATE `data` SET `list`='Peter Skewes' WHERE `list`='Skewes%% Peter';
UPDATE `data` SET `list`='Maureen Smith' WHERE `list`='Smith%% Maureen';
UPDATE `data` SET `list`='Jill Stein' WHERE `list`='Stein%% Jill';
UPDATE `data` SET `list`='Thomas R. Stevens' WHERE `list`='Stevens%% Thomas R.';
UPDATE `data` SET `list`='Thomas Robert "Tom" Stevens' WHERE `list`='Stevens%% Thomas Robert "Tom"';
UPDATE `data` SET `list`='Timothy Allen Stevens' WHERE `list`='Stevens%% Timothy Allen';
UPDATE `data` SET `list`='Christopher Stried' WHERE `list`='Stried%% Christopher';
UPDATE `data` SET `list`='James Timothy Struck' WHERE `list`='Struck%% James Timothy';
UPDATE `data` SET `list`='Chris Sununu' WHERE `list`='Sununu%% Chris';
UPDATE `data` SET `list`='Vermin Supreme' WHERE `list`='Supreme%% Vermin';
UPDATE `data` SET `list`='Gary Swing' WHERE `list`='Swing%% Gary';
UPDATE `data` SET `list`='Diane Templin' WHERE `list`='Templin%% Diane';
UPDATE `data` SET `list`='Randall Terry' WHERE `list`='Terry%% Randall';
UPDATE `data` SET `list`='The Better Life' WHERE `list`='The Better Life%%';
UPDATE `data` SET `list`='Sheila "Samm" Tittle' WHERE `list`='Tittle%% Sheila "Samm"';
UPDATE `data` SET `list`='Donald J. Trump' WHERE `list`='Trump%% Donald J.';
UPDATE `data` SET `list`='Dan Vacek' WHERE `list`='Vacek%% Dan';
UPDATE `data` SET `list`='Bill Van Auken' WHERE `list`='Van Auken%% Bill';
UPDATE `data` SET `list`='Angela Walls-Windhauser' WHERE `list`='Walls-Windhauser%% Angela';
UPDATE `data` SET `list`='Jeffrey Wamboldt' WHERE `list`='Wamboldt%% Jeffrey';
UPDATE `data` SET `list`='James "Mac" Warren' WHERE `list`='Warren%% James "Mac"';
UPDATE `data` SET `list`='Barbara Dale Washer' WHERE `list`='Washer%% Barbara Dale';
UPDATE `data` SET `list`='Ted Weill' WHERE `list`='Weill%% Ted';
UPDATE `data` SET `list`='Karynn Krill Weinstein' WHERE `list`='Weinstein%% Karynn Krill';
UPDATE `data` SET `list`='Bill Weld' WHERE `list`='Weld%% Bill';
UPDATE `data` SET `list`='Kasey Wells' WHERE `list`='Wells%% Kasey';
UPDATE `data` SET `list`='Martin E. Wendelken' WHERE `list`='Wendelken%% Martin E.';
UPDATE `data` SET `list`='Kanye West' WHERE `list`='West%% Kanye';
UPDATE `data` SET `list`='Jerome "Jerry" White' WHERE `list`='White%% Jerome "Jerry"';
UPDATE `data` SET `list`='Jerry White' WHERE `list`='White%% Jerry';
UPDATE `data` SET `list`='Andy Williams Jr.' WHERE `list`='Williams Jr.%% Andy';
UPDATE `data` SET `list`='Mitchell Williams' WHERE `list`='Williams%% Mitchell';
UPDATE `data` SET `list`='Edward Winn' WHERE `list`='Winn%% Edward';
UPDATE `data` SET `list`='Margaret Wright' WHERE `list`='Wright%% Margaret';
UPDATE `data` SET `list`='Andrew Yang' WHERE `list`='Yang%% Andrew';
UPDATE `data` SET `list`='John Yiamouyiannis' WHERE `list`='Yiamouyiannis%% John';
UPDATE `data` SET `list`='Louie G. Youngkeit' WHERE `list`='Youngkeit%% Louie G.';
UPDATE `data` SET `list`='Frank Zeidler' WHERE `list`='Zeidler%% Frank';
